version: '3.9'
services:
  app:
    image: ma_super_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: my_database
      DB_USERNAME: my_username
      DB_PASSWORD: my_password
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
